# Generated by Django 4.0 on 2022-03-23 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='도_광역시',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('이름', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='지역',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('이름', models.CharField(max_length=40)),
                ('도_광역시', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.도_광역시')),
            ],
        ),
        migrations.CreateModel(
            name='재활센터',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('이름', models.CharField(max_length=70)),
                ('주소', models.CharField(max_length=200)),
                ('정보', models.CharField(max_length=1400)),
                ('싸이트', models.CharField(max_length=200)),
                ('위도', models.CharField(max_length=200)),
                ('경도', models.CharField(max_length=200)),
                ('센터', models.BooleanField(default=False)),
                ('가정방문', models.BooleanField(default=False)),
                ('전화번호', models.CharField(max_length=60)),
                ('지역', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.지역')),
            ],
        ),
    ]
