# Generated by Django 4.0 on 2022-04-05 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='도_광역시',
            options={'verbose_name_plural': '도_광역시'},
        ),
        migrations.AlterModelOptions(
            name='재활센터',
            options={'verbose_name_plural': '재활센터'},
        ),
        migrations.AlterModelOptions(
            name='지역',
            options={'verbose_name_plural': '소도시_지역'},
        ),
        migrations.AlterField(
            model_name='도_광역시',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
