# Generated by Django 4.0 on 2022-04-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_도_광역시_options_alter_재활센터_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='재활센터',
            name='사진',
            field=models.ImageField(default='logo.png', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='재활센터',
            name='전화번호',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
