# Generated by Django 4.0 on 2022-04-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_재활센터_사진_alter_재활센터_전화번호'),
    ]

    operations = [
        migrations.AlterField(
            model_name='재활센터',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='지역',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
