# Generated by Django 4.0 on 2022-04-11 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_rename_싸이트_재활센터_웹사이트_alter_재활센터_정보'),
    ]

    operations = [
        migrations.AddField(
            model_name='도_광역시',
            name='번호',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='재활센터',
            name='번호',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='지역',
            name='번호',
            field=models.IntegerField(default=0),
        ),
    ]
